# As config was originally based on an example by Olivier Grisel. Thanks!
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml

clone_depth: 50

# No reason for us to restrict the number concurrent jobs
max_jobs: 100

environment:
  global:
    # Wrapper to ensure extensions are build using the MSVC compiler matching
    # the target Python version and architecture.
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: 'cmd /E:ON /V:ON /C .\tests\scripts\appveyor\run_with_env.cmd'

  PYTEST: py.test --maxfail 5 --durations=10 --junitxml=junit-results.xml
  # Break the tests into two runs, since together they exceed the 1 hour limit.
  # See https://github.com/pyinstaller/pyinstaller/issues/2024#issuecomment-224129520
  # for more discussion.
  TESTS_UNITTESTS: tests/unit tests/functional -k "not tests/functional/test_libraries.py"
  TESTS_LIBRARIES: tests/functional/test_libraries.py

  matrix:
    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64
      TEST_LIBRARIES: NO

    - PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32
      TEST_LIBRARIES: NO

    - PYTHON: C:\Python35
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32
      TEST_LIBRARIES: NO

    - PYTHON: C:\Python34
      PYTHON_VERSION: 3.4
      PYTHON_ARCH: 32
      TEST_LIBRARIES: NO

    - PYTHON: C:\Python33
      PYTHON_VERSION: 3.3
      PYTHON_ARCH: 32
      TEST_LIBRARIES: NO

    - PYTHON: C:\Python27
      PYTHON_VERSION: 2.7
      PYTHON_ARCH: 32
      TEST_LIBRARIES: NO


init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - ECHO "%APPVEYOR_SCHEDULED_BUILD%"

cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'

install:
  - C:\cygwin\bin\du -hs "%LOCALAPPDATA%\pip\Cache"
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - >-
     %CMD_IN_ENV%
     python -c "import sys,platform,struct;
     print(sys.platform, platform.machine(), struct.calcsize('P') * 8, )"

  # Compile bootloader.
  - cd bootloader
  - python waf all --target-arch=%PYTHON_ARCH%bit
  # Verify the bootloaders have the expected arch
  - python ../tests/scripts/check-pefile-arch.py %PYTHON_ARCH% build/*/*.exe
  - cd ..

build: none

test_script:
  # Run the tests appropriate for this entry in the test matrix. Skip tests
  # if we're just updating the cache.
  - echo no-tests
